Add minHour and maxHour to be displayed in day/week view
acro5piano/react-native-big-calendar pull request #1050
Opened 2024-05-31 09:00 UTC by adambinnersley

2024-05-31 14:00 UTC, acro5piano approved these changes
Thank you very much! Some minor tweaks are needed but it's almost there.

2024-05-31 14:00 UTC, acro5piano commented on src/components/CalendarBody.tsx
> +      : Array.from(Array(24).keys())
Can you validate it in `CalendarContainer.tsx`? like

```ts
if (minHour >= maxHour) { 
  throw new Error('minHour should be greater than maxHour')
}
if (minHour <= 0) { 
  // other error message
}
// other checks
```

I think it's more intuitive to provide developers comprehensive error message than defaulting the basic.

2024-05-31 14:00 UTC, acro5piano commented on README.md
> +| `maxHour`                  | no       | `number`                                 | The final hour that will be displayed in week/day modes.
Thanks,

If you provide examples in the storybook, it's helpful (not mandatory though)

2024-05-31 14:01 UTC, acro5piano requested changes
Sorry I wanted to request changes. misclicked!

2024-05-31 14:41 UTC, adambinnersley commented
I've updated to fork to now throw errors on incorrect prop values and added a story to demonstate these new props

2024-06-02 14:18 UTC, acro5piano commented
@adambinnersley Fantasitc! Thank you for your great work!

2024-06-02 14:18 UTC, merged

2024-06-07 15:15 UTC, jangminhyeok commented
#1053 Hi, There is a problem with event cell position. It happens in iOS 17.4 / iPhone 15 Pro Max. By the way, thank you for your contribution!