Add RTL support
acro5piano/react-native-big-calendar pull request #270
Opened 2020-10-19 13:44 UTC by Gilad-Shnoor

2020-10-19 14:35 UTC, acro5piano requested changes
Thank you for your contribution. I love it.
In addtion, 

- Can you add `isRTL` to the API documentation?

https://github.com/acro5piano/react-native-big-calendar#api-documentation

- Can you add a story for describing RTL support?

https://github.com/acro5piano/react-native-big-calendar/blob/master/stories/desktop.stories.tsx

Thanks very much!

2020-10-19 14:35 UTC, acro5piano commented on src/Calendar.tsx
> +
Can you remove this?

2020-10-20 06:31 UTC, Gilad-Shnoor commented
done

2020-10-20 06:42 UTC, acro5piano approved these changes
Thanks!!

2020-10-20 06:43 UTC, acro5piano commented
@Gilad-Shnoor Thank you for your contribution!

2020-10-20 06:43 UTC, merged

2020-10-20 06:55 UTC, acro5piano commented
Released in v0.7.0

https://github.com/acro5piano/react-native-big-calendar/releases/tag/v0.7.0