Feat custom event renderer // Fix types
acro5piano/react-native-big-calendar pull request #360
Opened 2021-03-23 14:51 UTC by sebastienfi

This fixes the typings on recent improvement https://github.com/acro5piano/react-native-big-calendar/pull/359

2021-03-23 14:56 UTC, acro5piano commented
Thanks for this PR too. Seems that GitHub actions not works for forked repo.

2021-03-23 15:05 UTC, acro5piano requested changes
Thanks very much!

2021-03-23 15:05 UTC, acro5piano commented on src/CalendarBody.tsx
> +                (start as dayjs.Dayjs).isBetween(date.startOf('day'), date.endOf('day'), null, '[)'),
Do you have any way to omit the castings `as dayjs.Dayjs`?
It should be more readable.

2021-03-23 15:26 UTC, acro5piano commented
@sebastienfi

Thank you for the PR. I've added a review for the typing.

https://github.com/acro5piano/react-native-big-calendar/pull/359

Sorry I thought GitHub actions checks typings, but it didn't. So if you fix type errors on that PR with this PR, I'd happy to merge them.

2021-03-23 17:18 UTC, sebastienfi commented
@acro5piano Done. Let me know if anything else.

2021-03-24 02:38 UTC, acro5piano commented
@sebastienfi Thanks!!

2021-03-24 02:47 UTC, acro5piano approved these changes

2021-03-24 02:47 UTC, merged